name: Deploy

on:
    workflow_dispatch:

jobs:
    infrastructure:
        runs-on: ubuntu-latest

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy CloudFormation stack
              run: |
                  aws cloudformation deploy \
                    --template-file deploy/aws.yaml \
                    --stack-name scc-app-cloudformation-stack \
                    --capabilities CAPABILITY_NAMED_IAM

            - name: Set up Python 3.
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install test dependencies
              run: pip3 install ansible-core boto3 botocore

            - name: Run Ansible playbook
              run: ansible-playbook deploy/deploy.yaml
