name: Infrastructure

on:
    workflow_dispatch:

jobs:
    infrastructure:
        runs-on: ubuntu-latest

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy CloudFormation stack
              run: |
                  aws cloudformation deploy \
                    --template-file infra/aws.yaml \
                    --stack-name scc-app-cloudformation-stack \
                    --capabilities CAPABILITY_NAMED_IAM
